/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Abrechnungsart__c
 */
public enum AbrechnungsartEnum {

    // Festpreis
    FESTPREIS("Festpreis"),
    // Time & Material
    TIME___MATERIAL("Time & Material");

    final String value;

    private AbrechnungsartEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AbrechnungsartEnum fromValue(String value) {
        for (AbrechnungsartEnum e : AbrechnungsartEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
