/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject Book__c
 */
@XStreamAlias("Book__c")
public class Book__c extends AbstractSObjectBase {

    // Price__c
    private Double Price__c;

    @JsonProperty("Price__c")
    public Double getPrice__c() {
        return this.Price__c;
    }

    @JsonProperty("Price__c")
    public void setPrice__c(Double Price__c) {
        this.Price__c = Price__c;
    }

}
