/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Branche__c
 */
public enum BrancheEnum {

    // Behörden
    BEHÖRDEN("Behörden"),
    // Retail
    RETAIL("Retail"),
    // Versicherungen
    VERSICHERUNGEN("Versicherungen");

    final String value;

    private BrancheEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BrancheEnum fromValue(String value) {
        for (BrancheEnum e : BrancheEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
