/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Festpreis_Zahlungsturnus__c
 */
public enum Festpreis_ZahlungsturnusEnum {

    // abgestimmt
    ABGESTIMMT("abgestimmt"),
    // monatlich
    MONATLICH("monatlich"),
    // quartalsweise
    QUARTALSWEISE("quartalsweise"),
    // wöchentlich
    WÖCHENTLICH("wöchentlich");

    final String value;

    private Festpreis_ZahlungsturnusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Festpreis_ZahlungsturnusEnum fromValue(String value) {
        for (Festpreis_ZahlungsturnusEnum e : Festpreis_ZahlungsturnusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
