/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Mitarbeiter__c
 */
public enum MitarbeiterEnum {

    // Benjamin Kling
    BENJAMIN_KLING("Benjamin Kling"),
    // India Bössinger
    INDIA_BÖSSINGER("India Bössinger"),
    // Ingo Sobik
    INGO_SOBIK("Ingo Sobik"),
    // Leoni Henner
    LEONI_HENNER("Leoni Henner"),
    // Max Grimm
    MAX_GRIMM("Max Grimm"),
    // Patrick Gabor
    PATRICK_GABOR("Patrick Gabor"),
    // Thomas Schorb
    THOMAS_SCHORB("Thomas Schorb"),
    // Torsten Naumann
    TORSTEN_NAUMANN("Torsten Naumann");

    final String value;

    private MitarbeiterEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static MitarbeiterEnum fromValue(String value) {
        for (MitarbeiterEnum e : MitarbeiterEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
