/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject Opportunity
 */
@XStreamAlias("Opportunity")
public class Opportunity extends AbstractSObjectBase {

    // AccountId
    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

    // IsPrivate
    private Boolean IsPrivate;

    @JsonProperty("IsPrivate")
    public Boolean getIsPrivate() {
        return this.IsPrivate;
    }

    @JsonProperty("IsPrivate")
    public void setIsPrivate(Boolean IsPrivate) {
        this.IsPrivate = IsPrivate;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // StageName
    @XStreamConverter(PicklistEnumConverter.class)
    private StageNameEnum StageName;

    @JsonProperty("StageName")
    public StageNameEnum getStageName() {
        return this.StageName;
    }

    @JsonProperty("StageName")
    public void setStageName(StageNameEnum StageName) {
        this.StageName = StageName;
    }

    // Amount
    private Double Amount;

    @JsonProperty("Amount")
    public Double getAmount() {
        return this.Amount;
    }

    @JsonProperty("Amount")
    public void setAmount(Double Amount) {
        this.Amount = Amount;
    }

    // Probability
    private Double Probability;

    @JsonProperty("Probability")
    public Double getProbability() {
        return this.Probability;
    }

    @JsonProperty("Probability")
    public void setProbability(Double Probability) {
        this.Probability = Probability;
    }

    // ExpectedRevenue
    private Double ExpectedRevenue;

    @JsonProperty("ExpectedRevenue")
    public Double getExpectedRevenue() {
        return this.ExpectedRevenue;
    }

    @JsonProperty("ExpectedRevenue")
    public void setExpectedRevenue(Double ExpectedRevenue) {
        this.ExpectedRevenue = ExpectedRevenue;
    }

    // TotalOpportunityQuantity
    private Double TotalOpportunityQuantity;

    @JsonProperty("TotalOpportunityQuantity")
    public Double getTotalOpportunityQuantity() {
        return this.TotalOpportunityQuantity;
    }

    @JsonProperty("TotalOpportunityQuantity")
    public void setTotalOpportunityQuantity(Double TotalOpportunityQuantity) {
        this.TotalOpportunityQuantity = TotalOpportunityQuantity;
    }

    // CloseDate
    private org.joda.time.DateTime CloseDate;

    @JsonProperty("CloseDate")
    public org.joda.time.DateTime getCloseDate() {
        return this.CloseDate;
    }

    @JsonProperty("CloseDate")
    public void setCloseDate(org.joda.time.DateTime CloseDate) {
        this.CloseDate = CloseDate;
    }

    // Type
    @XStreamConverter(PicklistEnumConverter.class)
    private TypeEnum Type;

    @JsonProperty("Type")
    public TypeEnum getType() {
        return this.Type;
    }

    @JsonProperty("Type")
    public void setType(TypeEnum Type) {
        this.Type = Type;
    }

    // NextStep
    private String NextStep;

    @JsonProperty("NextStep")
    public String getNextStep() {
        return this.NextStep;
    }

    @JsonProperty("NextStep")
    public void setNextStep(String NextStep) {
        this.NextStep = NextStep;
    }

    // LeadSource
    @XStreamConverter(PicklistEnumConverter.class)
    private LeadSourceEnum LeadSource;

    @JsonProperty("LeadSource")
    public LeadSourceEnum getLeadSource() {
        return this.LeadSource;
    }

    @JsonProperty("LeadSource")
    public void setLeadSource(LeadSourceEnum LeadSource) {
        this.LeadSource = LeadSource;
    }

    // IsClosed
    private Boolean IsClosed;

    @JsonProperty("IsClosed")
    public Boolean getIsClosed() {
        return this.IsClosed;
    }

    @JsonProperty("IsClosed")
    public void setIsClosed(Boolean IsClosed) {
        this.IsClosed = IsClosed;
    }

    // IsWon
    private Boolean IsWon;

    @JsonProperty("IsWon")
    public Boolean getIsWon() {
        return this.IsWon;
    }

    @JsonProperty("IsWon")
    public void setIsWon(Boolean IsWon) {
        this.IsWon = IsWon;
    }

    // ForecastCategory
    @XStreamConverter(PicklistEnumConverter.class)
    private ForecastCategoryEnum ForecastCategory;

    @JsonProperty("ForecastCategory")
    public ForecastCategoryEnum getForecastCategory() {
        return this.ForecastCategory;
    }

    @JsonProperty("ForecastCategory")
    public void setForecastCategory(ForecastCategoryEnum ForecastCategory) {
        this.ForecastCategory = ForecastCategory;
    }

    // ForecastCategoryName
    @XStreamConverter(PicklistEnumConverter.class)
    private ForecastCategoryNameEnum ForecastCategoryName;

    @JsonProperty("ForecastCategoryName")
    public ForecastCategoryNameEnum getForecastCategoryName() {
        return this.ForecastCategoryName;
    }

    @JsonProperty("ForecastCategoryName")
    public void setForecastCategoryName(ForecastCategoryNameEnum ForecastCategoryName) {
        this.ForecastCategoryName = ForecastCategoryName;
    }

    // CampaignId
    private String CampaignId;

    @JsonProperty("CampaignId")
    public String getCampaignId() {
        return this.CampaignId;
    }

    @JsonProperty("CampaignId")
    public void setCampaignId(String CampaignId) {
        this.CampaignId = CampaignId;
    }

    // HasOpportunityLineItem
    private Boolean HasOpportunityLineItem;

    @JsonProperty("HasOpportunityLineItem")
    public Boolean getHasOpportunityLineItem() {
        return this.HasOpportunityLineItem;
    }

    @JsonProperty("HasOpportunityLineItem")
    public void setHasOpportunityLineItem(Boolean HasOpportunityLineItem) {
        this.HasOpportunityLineItem = HasOpportunityLineItem;
    }

    // Pricebook2Id
    private String Pricebook2Id;

    @JsonProperty("Pricebook2Id")
    public String getPricebook2Id() {
        return this.Pricebook2Id;
    }

    @JsonProperty("Pricebook2Id")
    public void setPricebook2Id(String Pricebook2Id) {
        this.Pricebook2Id = Pricebook2Id;
    }

    // FiscalQuarter
    private Integer FiscalQuarter;

    @JsonProperty("FiscalQuarter")
    public Integer getFiscalQuarter() {
        return this.FiscalQuarter;
    }

    @JsonProperty("FiscalQuarter")
    public void setFiscalQuarter(Integer FiscalQuarter) {
        this.FiscalQuarter = FiscalQuarter;
    }

    // FiscalYear
    private Integer FiscalYear;

    @JsonProperty("FiscalYear")
    public Integer getFiscalYear() {
        return this.FiscalYear;
    }

    @JsonProperty("FiscalYear")
    public void setFiscalYear(Integer FiscalYear) {
        this.FiscalYear = FiscalYear;
    }

    // Fiscal
    private String Fiscal;

    @JsonProperty("Fiscal")
    public String getFiscal() {
        return this.Fiscal;
    }

    @JsonProperty("Fiscal")
    public void setFiscal(String Fiscal) {
        this.Fiscal = Fiscal;
    }

    // Festpreis_Zahlungszieldatum__c
    private org.joda.time.DateTime Festpreis_Zahlungszieldatum__c;

    @JsonProperty("Festpreis_Zahlungszieldatum__c")
    public org.joda.time.DateTime getFestpreis_Zahlungszieldatum__c() {
        return this.Festpreis_Zahlungszieldatum__c;
    }

    @JsonProperty("Festpreis_Zahlungszieldatum__c")
    public void setFestpreis_Zahlungszieldatum__c(org.joda.time.DateTime Festpreis_Zahlungszieldatum__c) {
        this.Festpreis_Zahlungszieldatum__c = Festpreis_Zahlungszieldatum__c;
    }

    // TrackingNumber__c
    private String TrackingNumber__c;

    @JsonProperty("TrackingNumber__c")
    public String getTrackingNumber__c() {
        return this.TrackingNumber__c;
    }

    @JsonProperty("TrackingNumber__c")
    public void setTrackingNumber__c(String TrackingNumber__c) {
        this.TrackingNumber__c = TrackingNumber__c;
    }

    // Festpreis_Zahlungsturnus__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Festpreis_ZahlungsturnusEnum Festpreis_Zahlungsturnus__c;

    @JsonProperty("Festpreis_Zahlungsturnus__c")
    public Festpreis_ZahlungsturnusEnum getFestpreis_Zahlungsturnus__c() {
        return this.Festpreis_Zahlungsturnus__c;
    }

    @JsonProperty("Festpreis_Zahlungsturnus__c")
    public void setFestpreis_Zahlungsturnus__c(Festpreis_ZahlungsturnusEnum Festpreis_Zahlungsturnus__c) {
        this.Festpreis_Zahlungsturnus__c = Festpreis_Zahlungsturnus__c;
    }

    // Google_Drive_Projektskizze__c
    private String Google_Drive_Projektskizze__c;

    @JsonProperty("Google_Drive_Projektskizze__c")
    public String getGoogle_Drive_Projektskizze__c() {
        return this.Google_Drive_Projektskizze__c;
    }

    @JsonProperty("Google_Drive_Projektskizze__c")
    public void setGoogle_Drive_Projektskizze__c(String Google_Drive_Projektskizze__c) {
        this.Google_Drive_Projektskizze__c = Google_Drive_Projektskizze__c;
    }

    // Land__c
    @XStreamConverter(PicklistEnumConverter.class)
    private LandEnum Land__c;

    @JsonProperty("Land__c")
    public LandEnum getLand__c() {
        return this.Land__c;
    }

    @JsonProperty("Land__c")
    public void setLand__c(LandEnum Land__c) {
        this.Land__c = Land__c;
    }

    // Beauftragungsart__c
    @XStreamConverter(PicklistEnumConverter.class)
    private BeauftragungsartEnum Beauftragungsart__c;

    @JsonProperty("Beauftragungsart__c")
    public BeauftragungsartEnum getBeauftragungsart__c() {
        return this.Beauftragungsart__c;
    }

    @JsonProperty("Beauftragungsart__c")
    public void setBeauftragungsart__c(BeauftragungsartEnum Beauftragungsart__c) {
        this.Beauftragungsart__c = Beauftragungsart__c;
    }

    // Technologie__c
    @XStreamConverter(PicklistEnumConverter.class)
    private TechnologieEnum Technologie__c;

    @JsonProperty("Technologie__c")
    public TechnologieEnum getTechnologie__c() {
        return this.Technologie__c;
    }

    @JsonProperty("Technologie__c")
    public void setTechnologie__c(TechnologieEnum Technologie__c) {
        this.Technologie__c = Technologie__c;
    }

    // Produkte_Solutions__c
    private String Produkte_Solutions__c;

    @JsonProperty("Produkte_Solutions__c")
    public String getProdukte_Solutions__c() {
        return this.Produkte_Solutions__c;
    }

    @JsonProperty("Produkte_Solutions__c")
    public void setProdukte_Solutions__c(String Produkte_Solutions__c) {
        this.Produkte_Solutions__c = Produkte_Solutions__c;
    }

    // Beschreibung_Leadquelleninformationen__c
    private String Beschreibung_Leadquelleninformationen__c;

    @JsonProperty("Beschreibung_Leadquelleninformationen__c")
    public String getBeschreibung_Leadquelleninformationen__c() {
        return this.Beschreibung_Leadquelleninformationen__c;
    }

    @JsonProperty("Beschreibung_Leadquelleninformationen__c")
    public void setBeschreibung_Leadquelleninformationen__c(String Beschreibung_Leadquelleninformationen__c) {
        this.Beschreibung_Leadquelleninformationen__c = Beschreibung_Leadquelleninformationen__c;
    }

    // Gesch_ftsbereich__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Gesch_ftsbereichEnum Gesch_ftsbereich__c;

    @JsonProperty("Gesch_ftsbereich__c")
    public Gesch_ftsbereichEnum getGesch_ftsbereich__c() {
        return this.Gesch_ftsbereich__c;
    }

    @JsonProperty("Gesch_ftsbereich__c")
    public void setGesch_ftsbereich__c(Gesch_ftsbereichEnum Gesch_ftsbereich__c) {
        this.Gesch_ftsbereich__c = Gesch_ftsbereich__c;
    }

    // Angebotsnummer__c
    private String Angebotsnummer__c;

    @JsonProperty("Angebotsnummer__c")
    public String getAngebotsnummer__c() {
        return this.Angebotsnummer__c;
    }

    @JsonProperty("Angebotsnummer__c")
    public void setAngebotsnummer__c(String Angebotsnummer__c) {
        this.Angebotsnummer__c = Angebotsnummer__c;
    }

    // Datum_Beauftragung__c
    private org.joda.time.DateTime Datum_Beauftragung__c;

    @JsonProperty("Datum_Beauftragung__c")
    public org.joda.time.DateTime getDatum_Beauftragung__c() {
        return this.Datum_Beauftragung__c;
    }

    @JsonProperty("Datum_Beauftragung__c")
    public void setDatum_Beauftragung__c(org.joda.time.DateTime Datum_Beauftragung__c) {
        this.Datum_Beauftragung__c = Datum_Beauftragung__c;
    }

    // Projektstart_geplant__c
    private org.joda.time.DateTime Projektstart_geplant__c;

    @JsonProperty("Projektstart_geplant__c")
    public org.joda.time.DateTime getProjektstart_geplant__c() {
        return this.Projektstart_geplant__c;
    }

    @JsonProperty("Projektstart_geplant__c")
    public void setProjektstart_geplant__c(org.joda.time.DateTime Projektstart_geplant__c) {
        this.Projektstart_geplant__c = Projektstart_geplant__c;
    }

    // Projektende_geplant__c
    private org.joda.time.DateTime Projektende_geplant__c;

    @JsonProperty("Projektende_geplant__c")
    public org.joda.time.DateTime getProjektende_geplant__c() {
        return this.Projektende_geplant__c;
    }

    @JsonProperty("Projektende_geplant__c")
    public void setProjektende_geplant__c(org.joda.time.DateTime Projektende_geplant__c) {
        this.Projektende_geplant__c = Projektende_geplant__c;
    }

    // IstStart__c
    private org.joda.time.DateTime IstStart__c;

    @JsonProperty("IstStart__c")
    public org.joda.time.DateTime getIstStart__c() {
        return this.IstStart__c;
    }

    @JsonProperty("IstStart__c")
    public void setIstStart__c(org.joda.time.DateTime IstStart__c) {
        this.IstStart__c = IstStart__c;
    }

    // IstEnde__c
    private org.joda.time.DateTime IstEnde__c;

    @JsonProperty("IstEnde__c")
    public org.joda.time.DateTime getIstEnde__c() {
        return this.IstEnde__c;
    }

    @JsonProperty("IstEnde__c")
    public void setIstEnde__c(org.joda.time.DateTime IstEnde__c) {
        this.IstEnde__c = IstEnde__c;
    }

    // OpportunityInfo__c
    private String OpportunityInfo__c;

    @JsonProperty("OpportunityInfo__c")
    public String getOpportunityInfo__c() {
        return this.OpportunityInfo__c;
    }

    @JsonProperty("OpportunityInfo__c")
    public void setOpportunityInfo__c(String OpportunityInfo__c) {
        this.OpportunityInfo__c = OpportunityInfo__c;
    }

    // Sales_Pipe_Jahr__c
    private String Sales_Pipe_Jahr__c;

    @JsonProperty("Sales_Pipe_Jahr__c")
    public String getSales_Pipe_Jahr__c() {
        return this.Sales_Pipe_Jahr__c;
    }

    @JsonProperty("Sales_Pipe_Jahr__c")
    public void setSales_Pipe_Jahr__c(String Sales_Pipe_Jahr__c) {
        this.Sales_Pipe_Jahr__c = Sales_Pipe_Jahr__c;
    }

    // Google_Drive_Angebot__c
    private String Google_Drive_Angebot__c;

    @JsonProperty("Google_Drive_Angebot__c")
    public String getGoogle_Drive_Angebot__c() {
        return this.Google_Drive_Angebot__c;
    }

    @JsonProperty("Google_Drive_Angebot__c")
    public void setGoogle_Drive_Angebot__c(String Google_Drive_Angebot__c) {
        this.Google_Drive_Angebot__c = Google_Drive_Angebot__c;
    }

    // Quartal__c
    private String Quartal__c;

    @JsonProperty("Quartal__c")
    public String getQuartal__c() {
        return this.Quartal__c;
    }

    @JsonProperty("Quartal__c")
    public void setQuartal__c(String Quartal__c) {
        this.Quartal__c = Quartal__c;
    }

    // Option_Verl_ngerung__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Option_Verl_ngerungEnum Option_Verl_ngerung__c;

    @JsonProperty("Option_Verl_ngerung__c")
    public Option_Verl_ngerungEnum getOption_Verl_ngerung__c() {
        return this.Option_Verl_ngerung__c;
    }

    @JsonProperty("Option_Verl_ngerung__c")
    public void setOption_Verl_ngerung__c(Option_Verl_ngerungEnum Option_Verl_ngerung__c) {
        this.Option_Verl_ngerung__c = Option_Verl_ngerung__c;
    }

    // Geplante_PT__c
    private Double Geplante_PT__c;

    @JsonProperty("Geplante_PT__c")
    public Double getGeplante_PT__c() {
        return this.Geplante_PT__c;
    }

    @JsonProperty("Geplante_PT__c")
    public void setGeplante_PT__c(Double Geplante_PT__c) {
        this.Geplante_PT__c = Geplante_PT__c;
    }

    // Aktives_Projekt__c
    private Boolean Aktives_Projekt__c;

    @JsonProperty("Aktives_Projekt__c")
    public Boolean getAktives_Projekt__c() {
        return this.Aktives_Projekt__c;
    }

    @JsonProperty("Aktives_Projekt__c")
    public void setAktives_Projekt__c(Boolean Aktives_Projekt__c) {
        this.Aktives_Projekt__c = Aktives_Projekt__c;
    }

    // TagessatzMax__c
    private Double TagessatzMax__c;

    @JsonProperty("TagessatzMax__c")
    public Double getTagessatzMax__c() {
        return this.TagessatzMax__c;
    }

    @JsonProperty("TagessatzMax__c")
    public void setTagessatzMax__c(Double TagessatzMax__c) {
        this.TagessatzMax__c = TagessatzMax__c;
    }

    // TagessatzMin__c
    private Double TagessatzMin__c;

    @JsonProperty("TagessatzMin__c")
    public Double getTagessatzMin__c() {
        return this.TagessatzMin__c;
    }

    @JsonProperty("TagessatzMin__c")
    public void setTagessatzMin__c(Double TagessatzMin__c) {
        this.TagessatzMin__c = TagessatzMin__c;
    }

    // Beschreibung__c
    private String Beschreibung__c;

    @JsonProperty("Beschreibung__c")
    public String getBeschreibung__c() {
        return this.Beschreibung__c;
    }

    @JsonProperty("Beschreibung__c")
    public void setBeschreibung__c(String Beschreibung__c) {
        this.Beschreibung__c = Beschreibung__c;
    }

    // Beschreibung_Bestandteile_Angebot__c
    private String Beschreibung_Bestandteile_Angebot__c;

    @JsonProperty("Beschreibung_Bestandteile_Angebot__c")
    public String getBeschreibung_Bestandteile_Angebot__c() {
        return this.Beschreibung_Bestandteile_Angebot__c;
    }

    @JsonProperty("Beschreibung_Bestandteile_Angebot__c")
    public void setBeschreibung_Bestandteile_Angebot__c(String Beschreibung_Bestandteile_Angebot__c) {
        this.Beschreibung_Bestandteile_Angebot__c = Beschreibung_Bestandteile_Angebot__c;
    }

    // Geplanter_Berater_1__c
    private String Geplanter_Berater_1__c;

    @JsonProperty("Geplanter_Berater_1__c")
    public String getGeplanter_Berater_1__c() {
        return this.Geplanter_Berater_1__c;
    }

    @JsonProperty("Geplanter_Berater_1__c")
    public void setGeplanter_Berater_1__c(String Geplanter_Berater_1__c) {
        this.Geplanter_Berater_1__c = Geplanter_Berater_1__c;
    }

    // Geplanter_Berater_2__c
    private String Geplanter_Berater_2__c;

    @JsonProperty("Geplanter_Berater_2__c")
    public String getGeplanter_Berater_2__c() {
        return this.Geplanter_Berater_2__c;
    }

    @JsonProperty("Geplanter_Berater_2__c")
    public void setGeplanter_Berater_2__c(String Geplanter_Berater_2__c) {
        this.Geplanter_Berater_2__c = Geplanter_Berater_2__c;
    }

    // Geplanter_Berater_3__c
    private String Geplanter_Berater_3__c;

    @JsonProperty("Geplanter_Berater_3__c")
    public String getGeplanter_Berater_3__c() {
        return this.Geplanter_Berater_3__c;
    }

    @JsonProperty("Geplanter_Berater_3__c")
    public void setGeplanter_Berater_3__c(String Geplanter_Berater_3__c) {
        this.Geplanter_Berater_3__c = Geplanter_Berater_3__c;
    }

    // Branche__c
    @XStreamConverter(PicklistEnumConverter.class)
    private BrancheEnum Branche__c;

    @JsonProperty("Branche__c")
    public BrancheEnum getBranche__c() {
        return this.Branche__c;
    }

    @JsonProperty("Branche__c")
    public void setBranche__c(BrancheEnum Branche__c) {
        this.Branche__c = Branche__c;
    }

    // Abrechnungsart__c
    @XStreamConverter(PicklistEnumConverter.class)
    private AbrechnungsartEnum Abrechnungsart__c;

    @JsonProperty("Abrechnungsart__c")
    public AbrechnungsartEnum getAbrechnungsart__c() {
        return this.Abrechnungsart__c;
    }

    @JsonProperty("Abrechnungsart__c")
    public void setAbrechnungsart__c(AbrechnungsartEnum Abrechnungsart__c) {
        this.Abrechnungsart__c = Abrechnungsart__c;
    }

    // Best__c
    private String Best__c;

    @JsonProperty("Best__c")
    public String getBest__c() {
        return this.Best__c;
    }

    @JsonProperty("Best__c")
    public void setBest__c(String Best__c) {
        this.Best__c = Best__c;
    }

    // Ansprechpartner_Kunde__c
    private String Ansprechpartner_Kunde__c;

    @JsonProperty("Ansprechpartner_Kunde__c")
    public String getAnsprechpartner_Kunde__c() {
        return this.Ansprechpartner_Kunde__c;
    }

    @JsonProperty("Ansprechpartner_Kunde__c")
    public void setAnsprechpartner_Kunde__c(String Ansprechpartner_Kunde__c) {
        this.Ansprechpartner_Kunde__c = Ansprechpartner_Kunde__c;
    }

    // Quartal_einzeln__c
    @XStreamConverter(PicklistEnumConverter.class)
    private Quartal_einzelnEnum Quartal_einzeln__c;

    @JsonProperty("Quartal_einzeln__c")
    public Quartal_einzelnEnum getQuartal_einzeln__c() {
        return this.Quartal_einzeln__c;
    }

    @JsonProperty("Quartal_einzeln__c")
    public void setQuartal_einzeln__c(Quartal_einzelnEnum Quartal_einzeln__c) {
        this.Quartal_einzeln__c = Quartal_einzeln__c;
    }

}
