/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Option_Verl_ngerung__c
 */
public enum Option_Verl_ngerungEnum {

    // Ja
    JA("Ja"),
    // Nein
    NEIN("Nein");

    final String value;

    private Option_Verl_ngerungEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Option_Verl_ngerungEnum fromValue(String value) {
        for (Option_Verl_ngerungEnum e : Option_Verl_ngerungEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
