/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Person_Typ__c
 */
public enum Person_TypEnum {

    // Aufsichtsrat
    AUFSICHTSRAT("Aufsichtsrat"),
    // Freelancer
    FREELANCER("Freelancer"),
    // Kundenkontakt
    KUNDENKONTAKT("Kundenkontakt"),
    // Mitarbeiter
    MITARBEITER("Mitarbeiter"),
    // Partner
    PARTNER("Partner"),
    // Praktikant
    PRAKTIKANT("Praktikant");

    final String value;

    private Person_TypEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Person_TypEnum fromValue(String value) {
        for (Person_TypEnum e : Person_TypEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
