/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Quartal_einzeln__c
 */
public enum Quartal_einzelnEnum {

    // Q1
    Q1("Q1"),
    // Q2
    Q2("Q2"),
    // Q3
    Q3("Q3"),
    // Q4
    Q4("Q4");

    final String value;

    private Quartal_einzelnEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Quartal_einzelnEnum fromValue(String value) {
        for (Quartal_einzelnEnum e : Quartal_einzelnEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
