/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist RecurrenceInstance
 */
public enum RecurrenceInstanceEnum {

    // First
    FIRST("First"),
    // Fourth
    FOURTH("Fourth"),
    // Last
    LAST("Last"),
    // Second
    SECOND("Second"),
    // Third
    THIRD("Third");

    final String value;

    private RecurrenceInstanceEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RecurrenceInstanceEnum fromValue(String value) {
        for (RecurrenceInstanceEnum e : RecurrenceInstanceEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
