/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist StageName
 */
public enum StageNameEnum {

    // Geschlossen und gewonnen
    GESCHLOSSEN_UND_GEWONNEN("Geschlossen und gewonnen"),
    // Geschlossen und verloren
    GESCHLOSSEN_UND_VERLOREN("Geschlossen und verloren"),
    // Id. Decision Makers
    ID__DECISION_MAKERS("Id. Decision Makers"),
    // Needs Analysis
    NEEDS_ANALYSIS("Needs Analysis"),
    // Negotiation/Review
    NEGOTIATION_REVIEW("Negotiation/Review"),
    // Perception Analysis
    PERCEPTION_ANALYSIS("Perception Analysis"),
    // Proposal/Price Quote
    PROPOSAL_PRICE_QUOTE("Proposal/Price Quote"),
    // Prospecting
    PROSPECTING("Prospecting"),
    // Qualification
    QUALIFICATION("Qualification"),
    // Value Proposition
    VALUE_PROPOSITION("Value Proposition");

    final String value;

    private StageNameEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static StageNameEnum fromValue(String value) {
        for (StageNameEnum e : StageNameEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
