/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
public enum TypeEnum {

    // Month
    MONTH("Month"),
    // Quarter
    QUARTER("Quarter"),
    // Week
    WEEK("Week"),
    // Year
    YEAR("Year"),
    // Account Data
    KUNDE("Kunde"),
    // Account Data
    INTERESSENT("Interessent"),
    // Account Data
    PARTNER("Partner"),
    // General Data
    NULL(null);

    final String value;

    private TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
        for (TypeEnum e : TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
