/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Jun 17 11:02:28 CEST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Verf_gbarkeit__c
 */
public enum Verf_gbarkeitEnum {

    // 1 Tag
    _1_TAG("1 Tag"),
    // 2 Tage
    _2_TAGE("2 Tage"),
    // 3 Tage
    _3_TAGE("3 Tage"),
    // 4 Tage
    _4_TAGE("4 Tage"),
    // 5 Tage
    _5_TAGE("5 Tage"),
    // Auf Abruf
    AUF_ABRUF("Auf Abruf"),
    // Sporadisch
    SPORADISCH("Sporadisch");

    final String value;

    private Verf_gbarkeitEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Verf_gbarkeitEnum fromValue(String value) {
        for (Verf_gbarkeitEnum e : Verf_gbarkeitEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
